### PR TITLE
Fix XSS issue

### PR DESCRIPTION
**Pull request by M0ck3d**
Fix the stored XSS vulnerability on the User Home and Profile Page.

### CODE REVIEW

**Review by fobybus — CHANGES_REQUESTED** [review]
your patch is great but it doesn't prevent the injection. malicious users can inject the other fields like a date by modifying  post data sent to the server. other problem is it's very difficult to maintain the code in the future if we just added the sanitization during the output. Its better to filter once during registration in signup.php, admin/atask/add.php setting.php

**Comment by M0ck3d** [comment]
Updated code, Please review

**Comment by fobybus** [comment]
Well done

**Review by fobybus — COMMENTED** [review]
nice work

**Comment by M0ck3d** [comment]
Glad to help ! I really appreciate you walking me though the correct fix

**Pull request merged**
